version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static-box:/static-box
  faketerest:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/faketerest/.env
      - ./next.config.js:/faketerest/.next.config.js
      - ./pages:/faketerest/pages
      - ./src:/faketerest/src
      - ./static-box:/faketerest/static-box
    depends_on:
      - redis
      - postgres
      - pager
      - nginx
    links:
      - 'redis:redis'
      - 'pager:pager'
      - 'postgres:postgres'
  pager:
    build: ./faketerest-pager
    ports:
      - '3003:3003'
    links:
      - 'postgres:postgres'
    depends_on:
      - redis
      - postgres
      - nginx
  redis:
    image: redis:5.0.14
    command: redis-server /redis.conf --requirepass ${REDIS_DB_PASS}
    volumes:
      - ./config/redis.conf:/redis.conf
    ports:
      - '${REDIS_DB_PORT}:6379'
  postgres:
    image: postgres:14-alpine
    restart: always
    tty: true
    volumes:
      - ./config/postgres-dump:/postgres/postgres-dump
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
