version: '3.3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - static_box:/static-box
      - ./public:/public
  faketerest:
    build: .
    volumes:
      - ./.env:/faketerest/.env
      - ./next.config.js:/faketerest/.next.config.js
      - ./pages:/faketerest/pages
      - ./src:/faketerest/src
      - static_box:/faketerest/static-box
      - ./locales:/faketerest/locales
      - ./public:/faketerest/public
    depends_on:
      - redis
      - postgres
      - pager
      - nginx
    links:
      - 'redis:redis'
      - 'pager:pager'
      - 'postgres:postgres'
  pager:
    user: "111:117"
    build: ./faketerest-pager
    links:
      - 'postgres:postgres'
    depends_on:
      - redis
      - postgres
      - nginx
  redis:
    image: redis:5.0.14
    command: redis-server /redis.conf --requirepass ${REDIS_DB_PASS}
    volumes:
      - ./config/redis.conf:/redis.conf
  postgres:
    image: postgres:14-alpine
    restart: always
    tty: true
    volumes:
      - ./config/postgres-dump:/postgres/postgres-dump
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres_data:
  static_box: